# Generated by Django 5.0.2 on 2024-02-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_purchase_datetime_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
